esphome:
  name: esp_somfy
  platform: ESP8266
  board: nodemcuv2
  
  arduino_version: espressif8266@2.3.2
  
  includes:
    - git-esphome-somfy/RFsomfy.h
    - git-esphome-somfy/SomfyRts.h
    - git-esphome-somfy/SomfyRts.cpp
    
  libraries:
    - ArduinoJson-esphomelib@5.13.3
    - Ticker

  comment: version 0.1 - 2020/04/13

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False
  baud_rate: 115200

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

binary_sensor:
  - platform: status
    name: "Somfy ESP Status"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Somfy ESP IP Address"
  - platform: version
    name: "RFsomfy version"
  - platform: custom
    lambda: |-
      auto rfSomfyInfo = new RFsomfyInfo();
      App.register_component(rfSomfyInfo);
      return {rfSomfyInfo};
    text_sensors:
      name: "RFsomfy info"

cover:
- platform: custom
  lambda: |-
    std::vector<Cover *> covers;
    auto rfSomfy0 = new RFsomfy(0);
    App.register_component(rfSomfy0);
    covers.push_back(rfSomfy0);
    return {covers};

  covers:
    - name: "Zonnetent"
      device_class: shade
      id: somfy0